% Program options
HapticOnList = {'ViconAP_001';'ViconAP_002'};

% A dialog to stop the loop
MessageBox = msgbox( 'Stop DataStream Client', 'Vicon DataStream SDK' );

% Load the SDK
fprintf( 'Loading SDK...' );
Client.LoadViconDataStreamSDK();
fprintf( 'done\n' );

% Program options
HostName = 'localhost:801';

% Make a new client
MyClient = Client();

% Connect to a server
fprintf( 'Connecting to %s ...', HostName );
while ~MyClient.IsConnected().Connected
    MyClient.Connect( HostName );
    fprintf( '.' );
end
fprintf( '\n' );

% Enable some different data types
MyClient.EnableSegmentData();
fprintf( 'Segment Data Enabled: %s\n',          AdaptBool( MyClient.IsSegmentDataEnabled().Enabled ) );

% Set the streaming mode
MyClient.SetStreamMode( StreamMode.ClientPull );

% Set the global up axis
MyClient.SetAxisMapping( Direction.Forward, ...
    Direction.Left,    ...
    Direction.Up );    % Z-up

Counter = 1;
% Loop until the message box is dismissed
while ishandle( MessageBox )
    drawnow;
    Counter = Counter + 1;

    % Get a frame
    fprintf( 'Waiting for new frame...' );
    while MyClient.GetFrame().Result.Value ~= Result.Success
        fprintf( '.' );
    end% while
    fprintf( '\n' );  

    % Get the frame number
    Output_GetFrameNumber = MyClient.GetFrameNumber();
    fprintf( 'Frame Number: %d\n', Output_GetFrameNumber.FrameNumber );

    % Get the timecode
    Output_GetTimecode = MyClient.GetTimecode();
    fprintf( 'Timecode: %dh %dm %ds %df %dsf %s %d %d %d\n\n',    ...
        Output_GetTimecode.Hours,                  ...
        Output_GetTimecode.Minutes,                ...
        Output_GetTimecode.Seconds,                ...
        Output_GetTimecode.Frames,                 ...
        Output_GetTimecode.SubFrame,               ...
        AdaptBool( Output_GetTimecode.FieldFlag ), ...
        Output_GetTimecode.Standard.Value,         ...
        Output_GetTimecode.SubFramesPerFrame,      ...
        Output_GetTimecode.UserBits );

    % Get the latency
    fprintf( 'Latency: %gs\n', MyClient.GetLatencyTotal().Total );

    % Count the number of subjects
    SubjectCount = MyClient.GetSubjectCount().SubjectCount;
    fprintf( 'Subjects (%d):\n', SubjectCount );
    for SubjectIndex = 1:SubjectCount
        fprintf( '  Subject #%d\n', SubjectIndex - 1 );

        % Get the subject name
        SubjectName = MyClient.GetSubjectName( SubjectIndex ).SubjectName;
        fprintf( '    Name: %s\n', SubjectName );

        % Get the root segment
        RootSegment = MyClient.GetSubjectRootSegmentName( SubjectName ).SegmentName;
        fprintf( '    Root Segment: %s\n', RootSegment );

        % Count the number of segments
        SegmentCount = MyClient.GetSegmentCount( SubjectName ).SegmentCount;
        fprintf( '    Segments (%d):\n', SegmentCount );
        for SegmentIndex = 1:SegmentCount
            fprintf( '      Segment #%d\n', SegmentIndex - 1 );

            % Get the segment name
            SegmentName = MyClient.GetSegmentName( SubjectName, SegmentIndex ).SegmentName;
            fprintf( '        Name: %s\n', SegmentName );

            % Get the segment parent
            SegmentParentName = MyClient.GetSegmentParentName( SubjectName, SegmentName ).SegmentName;
            fprintf( '        Parent: %s\n',  SegmentParentName );

            % Get the segment's children
            ChildCount = MyClient.GetSegmentChildCount( SubjectName, SegmentName ).SegmentCount;
            fprintf( '     Children (%d):\n', ChildCount );
            for ChildIndex = 1:ChildCount
                ChildName = MyClient.GetSegmentChildName( SubjectName, SegmentName, ChildIndex ).SegmentName;
                fprintf( '       %s\n', ChildName );
            end% for  

            % Get the static segment translation
            Output_GetSegmentStaticTranslation = MyClient.GetSegmentStaticTranslation( SubjectName, SegmentName );
            fprintf( '        Static Translation: (%g, %g, %g)\n',                  ...
                Output_GetSegmentStaticTranslation.Translation( 1 ), ...
                Output_GetSegmentStaticTranslation.Translation( 2 ), ...
                Output_GetSegmentStaticTranslation.Translation( 3 ) );

            % Get the static segment rotation in helical co-ordinates
            Output_GetSegmentStaticRotationHelical = MyClient.GetSegmentStaticRotationHelical( SubjectName, SegmentName );
            fprintf( '        Static Rotation Helical: (%g, %g, %g)\n',              ...
                Output_GetSegmentStaticRotationHelical.Rotation( 1 ), ...
                Output_GetSegmentStaticRotationHelical.Rotation( 2 ), ...
                Output_GetSegmentStaticRotationHelical.Rotation( 3 ) );

            % Get the static segment rotation as a matrix
            Output_GetSegmentStaticRotationMatrix = MyClient.GetSegmentStaticRotationMatrix( SubjectName, SegmentName );
            fprintf( '        Static Rotation Matrix: (%g, %g, %g, %g, %g, %g, %g, %g, %g)\n', ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 1 ),            ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 2 ),            ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 3 ),            ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 4 ),            ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 5 ),            ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 6 ),            ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 7 ),            ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 8 ),            ...
                Output_GetSegmentStaticRotationMatrix.Rotation( 9 ) );

            % Get the static segment rotation in quaternion co-ordinates
            Output_GetSegmentStaticRotationQuaternion = MyClient.GetSegmentStaticRotationQuaternion( SubjectName, SegmentName );
            fprintf( '        Static Rotation Quaternion: (%g, %g, %g, %g)\n',          ...
                Output_GetSegmentStaticRotationQuaternion.Rotation( 1 ), ...
                Output_GetSegmentStaticRotationQuaternion.Rotation( 2 ), ...
                Output_GetSegmentStaticRotationQuaternion.Rotation( 3 ), ...
                Output_GetSegmentStaticRotationQuaternion.Rotation( 4 ) );

            % Get the static segment rotation in EulerXYZ co-ordinates
            Output_GetSegmentStaticRotationEulerXYZ = MyClient.GetSegmentStaticRotationEulerXYZ( SubjectName, SegmentName );
            fprintf( '        Static Rotation EulerXYZ: (%g, %g, %g)\n',               ...
                Output_GetSegmentStaticRotationEulerXYZ.Rotation( 1 ),  ...
                Output_GetSegmentStaticRotationEulerXYZ.Rotation( 2 ),  ...
                Output_GetSegmentStaticRotationEulerXYZ.Rotation( 3 ) );

            % Get the global segment translation
            Output_GetSegmentGlobalTranslation = MyClient.GetSegmentGlobalTranslation( SubjectName, SegmentName );
            fprintf( '        Global Translation: (%g, %g, %g) %s\n',               ...
                Output_GetSegmentGlobalTranslation.Translation( 1 ), ...
                Output_GetSegmentGlobalTranslation.Translation( 2 ), ...
                Output_GetSegmentGlobalTranslation.Translation( 3 ), ...
                AdaptBool( Output_GetSegmentGlobalTranslation.Occluded ) );

            % Get the global segment rotation in helical co-ordinates
            Output_GetSegmentGlobalRotationHelical = MyClient.GetSegmentGlobalRotationHelical( SubjectName, SegmentName );
            fprintf( '        Global Rotation Helical: (%g, %g, %g) %s\n',           ...
                Output_GetSegmentGlobalRotationHelical.Rotation( 1 ), ...
                Output_GetSegmentGlobalRotationHelical.Rotation( 2 ), ...
                Output_GetSegmentGlobalRotationHelical.Rotation( 3 ), ...
                AdaptBool( Output_GetSegmentGlobalRotationHelical.Occluded ) );

            % Get the global segment rotation as a matrix
            Output_GetSegmentGlobalRotationMatrix = MyClient.GetSegmentGlobalRotationMatrix( SubjectName, SegmentName );
            fprintf( '        Global Rotation Matrix: (%g, %g, %g, %g, %g, %g, %g, %g, %g) %s\n', ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 1 ),               ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 2 ),               ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 3 ),               ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 4 ),               ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 5 ),               ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 6 ),               ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 7 ),               ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 8 ),               ...
                Output_GetSegmentGlobalRotationMatrix.Rotation( 9 ),               ...
                AdaptBool( Output_GetSegmentGlobalRotationMatrix.Occluded ) );

            % Get the global segment rotation in quaternion co-ordinates
            Output_GetSegmentGlobalRotationQuaternion = MyClient.GetSegmentGlobalRotationQuaternion( SubjectName, SegmentName );
            fprintf( '        Global Rotation Quaternion: (%g, %g, %g, %g) %s\n',             ...
                Output_GetSegmentGlobalRotationQuaternion.Rotation( 1 ),       ...
                Output_GetSegmentGlobalRotationQuaternion.Rotation( 2 ),       ...
                Output_GetSegmentGlobalRotationQuaternion.Rotation( 3 ),       ...
                Output_GetSegmentGlobalRotationQuaternion.Rotation( 4 ),       ...
                AdaptBool( Output_GetSegmentGlobalRotationQuaternion.Occluded ) );

            % Get the global segment rotation in EulerXYZ co-ordinates
            Output_GetSegmentGlobalRotationEulerXYZ = MyClient.GetSegmentGlobalRotationEulerXYZ( SubjectName, SegmentName );
            fprintf( '        Global Rotation EulerXYZ: (%g, %g, %g) %s\n',                 ...
                Output_GetSegmentGlobalRotationEulerXYZ.Rotation( 1 ),       ...
                Output_GetSegmentGlobalRotationEulerXYZ.Rotation( 2 ),       ...
                Output_GetSegmentGlobalRotationEulerXYZ.Rotation( 3 ),       ...
                AdaptBool( Output_GetSegmentGlobalRotationEulerXYZ.Occluded ) );

            % Get the local segment translation
            Output_GetSegmentLocalTranslation = MyClient.GetSegmentLocalTranslation( SubjectName, SegmentName );
            fprintf( '        Local Translation: (%g, %g, %g) %s\n',               ...
                Output_GetSegmentLocalTranslation.Translation( 1 ), ...
                Output_GetSegmentLocalTranslation.Translation( 2 ), ...
                Output_GetSegmentLocalTranslation.Translation( 3 ), ...
                AdaptBool( Output_GetSegmentLocalTranslation.Occluded ) );

            % Get the local segment rotation in helical co-ordinates
            Output_GetSegmentLocalRotationHelical = MyClient.GetSegmentLocalRotationHelical( SubjectName, SegmentName );
            fprintf( '        Local Rotation Helical: (%g, %g, %g) %s\n',           ...
                Output_GetSegmentLocalRotationHelical.Rotation( 1 ), ...
                Output_GetSegmentLocalRotationHelical.Rotation( 2 ), ...
                Output_GetSegmentLocalRotationHelical.Rotation( 3 ), ...
                AdaptBool( Output_GetSegmentLocalRotationHelical.Occluded ) );

            % Get the local segment rotation as a matrix
            Output_GetSegmentLocalRotationMatrix = MyClient.GetSegmentLocalRotationMatrix( SubjectName, SegmentName );
            fprintf( '        Local Rotation Matrix: (%g, %g, %g, %g, %g, %g, %g, %g, %g) %s\n', ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 1 ),               ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 2 ),               ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 3 ),               ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 4 ),               ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 5 ),               ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 6 ),               ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 7 ),               ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 8 ),               ...
                Output_GetSegmentLocalRotationMatrix.Rotation( 9 ),               ...
                AdaptBool( Output_GetSegmentLocalRotationMatrix.Occluded ) );

            % Get the local segment rotation in quaternion co-ordinates
            Output_GetSegmentLocalRotationQuaternion = MyClient.GetSegmentLocalRotationQuaternion( SubjectName, SegmentName );
            fprintf( '        Local Rotation Quaternion: (%g, %g, %g, %g) %s\n',             ...
                Output_GetSegmentLocalRotationQuaternion.Rotation( 1 ),       ...
                Output_GetSegmentLocalRotationQuaternion.Rotation( 2 ),       ...
                Output_GetSegmentLocalRotationQuaternion.Rotation( 3 ),       ...
                Output_GetSegmentLocalRotationQuaternion.Rotation( 4 ),       ...
                AdaptBool( Output_GetSegmentLocalRotationQuaternion.Occluded ) );

            % Get the local segment rotation in EulerXYZ co-ordinates
            Output_GetSegmentLocalRotationEulerXYZ = MyClient.GetSegmentLocalRotationEulerXYZ( SubjectName, SegmentName );
            fprintf( '        Local Rotation EulerXYZ: (%g, %g, %g) %s\n',                 ...
                Output_GetSegmentLocalRotationEulerXYZ.Rotation( 1 ),       ...
                Output_GetSegmentLocalRotationEulerXYZ.Rotation( 2 ),       ...
                Output_GetSegmentLocalRotationEulerXYZ.Rotation( 3 ),       ...
                AdaptBool( Output_GetSegmentLocalRotationEulerXYZ.Occluded ) );

        end% SegmentIndex

    end% SubjectIndex

end% while true  

% Disconnect and dispose
MyClient.Disconnect();

% Unload the SDK
fprintf( 'Unloading SDK...' );
Client.UnloadViconDataStreamSDK();
fprintf( 'done\n' );
